name: moon
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0
  retrofit: ^4.0.1
  json_annotation: ^4.8.0
  cupertino_icons: ^1.0.6
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3

  bloc: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.3.0
  retrofit_generator: ^5.0.0
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/moon.jpeg
    - assets/login.jpeg
    - assets/google_login.jpeg
    - assets/facebook_login.jpeg
    - assets/google_logo.jpg
    - assets/facebook_logo.png
