// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN0uFt3lf7czC8hfv14q1iFUFuwqX1nRQ',
    appId: '1:393235495413:web:1cfe46ce6bc71d6b9e08bc',
    messagingSenderId: '393235495413',
    projectId: 'moon-47845',
    authDomain: 'moon-47845.firebaseapp.com',
    storageBucket: 'moon-47845.appspot.com',
    measurementId: 'G-0FNSMYQSP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkhZmtaQTuH3D8UhaNTYBjAlsXVjgeUK0',
    appId: '1:393235495413:android:c0a57778a0e63a7a9e08bc',
    messagingSenderId: '393235495413',
    projectId: 'moon-47845',
    storageBucket: 'moon-47845.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQc6mv4cpB8o7APLecLNpyvCro1w_fFys',
    appId: '1:393235495413:ios:fa632a23465f36849e08bc',
    messagingSenderId: '393235495413',
    projectId: 'moon-47845',
    storageBucket: 'moon-47845.appspot.com',
    iosBundleId: 'com.example.moon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQc6mv4cpB8o7APLecLNpyvCro1w_fFys',
    appId: '1:393235495413:ios:fa632a23465f36849e08bc',
    messagingSenderId: '393235495413',
    projectId: 'moon-47845',
    storageBucket: 'moon-47845.appspot.com',
    iosBundleId: 'com.example.moon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN0uFt3lf7czC8hfv14q1iFUFuwqX1nRQ',
    appId: '1:393235495413:web:7cbf4f3c33c3c98f9e08bc',
    messagingSenderId: '393235495413',
    projectId: 'moon-47845',
    authDomain: 'moon-47845.firebaseapp.com',
    storageBucket: 'moon-47845.appspot.com',
    measurementId: 'G-KL5LE31EYS',
  );
}
